# Generated by Django 5.1.2 on 2024-10-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_alter_program_program_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=120),
        ),
    ]
