# Generated by Django 5.1.2 on 2024-10-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0003_alter_program_program_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Curriculum Years',
            },
        ),
    ]
