# Generated by Django 5.1.2 on 2024-10-19 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_curriculumyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_slot', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis.program')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis.curriculumyear')),
            ],
            options={
                'verbose_name_plural': 'ProgramSlots',
            },
        ),
    ]
