# Generated by Django 5.1.2 on 2024-10-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_programslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programslot',
            options={'verbose_name_plural': 'Program Slots'},
        ),
        migrations.AlterField(
            model_name='curriculumyear',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
