# Generated by Django 5.1.3 on 2024-11-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0007_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programs', models.CharField(max_length=255)),
                ('year_20_21', models.FloatField()),
                ('year_22_23', models.FloatField()),
                ('year_23_24', models.FloatField()),
                ('predicted_slots', models.FloatField()),
            ],
        ),
    ]
